sudo: false
language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
matrix:
  include:
    - name: "Frontend"
      language: node_js
      node_js: node
      before_install:
        - node --version
      install:
        - cd frontend
        - npm install
      script:
        - npm run builddev
        - npm run build
    - os: windows
      language: cpp
      python: "3.7"
      before_install:
       - choco install python --version 3.7.2
       - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      install:
       - pip install tox coveralls
install:
  - pip install tox-travis coveralls
script:
  - tox -vv
  - coveralls
