sudo: false
language: python
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - name: "Frontend"
      language: node_js
      node_js: node
      before_install:
        - node --version
      install:
        - cd frontend
        - npm install
      script:
        - npm run builddev
        - npm run build
install:
  - pip install tox-travis
script:
  - tox
